name: "Tests"

on:
  push:
    branches:
    - main-scylla
  pull_request:
    branches:
    - main-scylla

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.7
      - name: Set up requirements
        run: python -m pip install -r requirements.txt

      - name: Setup extension
        run: python setup.py install

      - name: Run tests
        run: python -m unittest --verbose
